### ISSUE TITLE
Handlers can land in-between snap points

### ISSUE THREAD

**Issue by mccjul** [DrChai/react-native-rheostat#1]
When you try to move a handler next to the other, the handler can snap in between specified snap points.

If you try on the example, drag one handler next to the other to achieve this bug.

**Comment by DrChai** [comment]
@mccjul By default, a handler cannot overlap with the next handle more than half of the slider width. so it could be stopped in between of snap points.

**Comment by therafi** [comment]
Feels weird, though. Expected behavior would be that the handle only stops at snap points. So if it is too close to the other handle, it should go back to the closest valid snap point, instead of stopping between snap points.

**Comment by DrChai** [comment]
fixed from https://github.com/DrChai/react-native-rheostat/commit/3a1331afffafb730abbbc994f484c7e7c921acb0
