### ISSUE TITLE
How to pass styles to this component

### ISSUE THREAD

**Issue by MuhammadAbdullah54321** [DrChai/react-native-rheostat#34]
I want to modify handles of slider ... want to change styles 
also I want to change the height of graph but i don't see any options available for that 
nor do i see them in documentation

**Comment by DrChai** [comment]
Sorry for the not perfect documentation, actually you can modify handles or  bar by passing `handle`  or `progressBar` to `withRheostat`: https://github.com/DrChai/react-native-rheostat/blob/master/src/hoc/withRheostat.tsx#L51. it uses `DefaultHandler` by default
