### ISSUE TITLE
moving the left slider button moves svg with it on android 

### ISSUE THREAD

**Issue by devkhan11** [DrChai/react-native-rheostat#6]
when sliding the left button slides the svg with it like fixed position it's not working like the examples shown in docs and also the right slider button is hidden when app is loaded and is shown when interacted with the slider
![SmartSelectImage_2020-02-11-11-50-20](https://user-images.githubusercontent.com/57259947/74217255-c7f34300-4cc8-11ea-8239-6645552cd52d.png)
![SmartSelectImage_2020-02-11-11-50-43](https://user-images.githubusercontent.com/57259947/74217259-c88bd980-4cc8-11ea-90c0-b96dfd9e4952.png)

**Comment by JongGyuChoi** [comment]
same issue here.. somebody help me!

**Comment by codingwaysarg** [comment]
same here :(. Any news?

**Comment by InfiniteDreamz** [comment]
Facing the exact same issue.

**Comment by InfiniteDreamz** [comment]
@DrChai @DrChai @codingwaysarg @JongGyuChoi Hey guyz, have you resolved this issue ?

**Comment by faboyds** [comment]
same happening on iOS

**Comment by krunalsperidian** [comment]
Any one got a solution for this..?

**Comment by krunalsperidian** [comment]
I guess there is some issues with some versions of reactnative.animation..
After updating RN versions 0.61.5  to 0.63.2 , this left button issue solved for me

**Comment by DrChai** [comment]
@InfiniteDreamz @faboyds haven't been managing this repo for 2years. I recently got some spare time from my main work and tried to play with this repo on both android and ios with up to date dependencies:
"d3-shape": "^2.1.0",
"react-native-svg-charts": "^5.4.0", 
"react": "^16.13.1",
"react-native": "0.63.3".
They all work correctly for me. But i will make a complete update soon, right now code just too aged to me.

**Comment by AE0011** [comment]
I fixed it
https://github.com/DrChai/react-native-rheostat/pull/25

**Comment by DrChai** [comment]
@AE0011 merged. Thanks for the improvement of BarChart, although it's not related to this bug.
